services:
  postgres:
    container_name: chatbridge_postgres
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  wwebjs:
    container_name: whatsapp_web_api
    image: avoylenko/wwebjs-api:latest # Pull the image from Docker Hub
    restart: always
    ports:
      - "4000:3000"
    environment:
      - API_KEY=${WHATSAPP_TOKEN} # OPTIONAL
      - BASE_WEBHOOK_URL=${BASE_WEBHOOK_URL}
      # - ENABLE_LOCAL_CALLBACK_EXAMPLE=TRUE # OPTIONAL, NOT RECOMMENDED FOR PRODUCTION
      - MAX_ATTACHMENT_SIZE=${MAX_ATTACHMENT_SIZE} # IN BYTES
      - SET_MESSAGES_AS_SEEN=${SET_MESSAGES_AS_SEEN} # WILL MARK THE MESSAGES AS READ AUTOMATICALLY
      # ALL CALLBACKS: auth_failure|authenticated|call|change_state|disconnected|group_join|group_leave|group_update|loading_screen|media_uploaded|message|message_ack|message_create|message_reaction|message_revoke_everyone|qr|ready|contact_changed
      # - DISABLED_CALLBACKS=message_ack|message_reaction  # PREVENT SENDING CERTAIN TYPES OF CALLBACKS BACK TO THE WEBHOOK
      - ENABLE_SWAGGER_ENDPOINT=${ENABLE_SWAGGER_ENDPOINT} # OPTIONAL, ENABLES THE /api-docs ENDPOINT
      # - RATE_LIMIT_MAX=1000 # OPTIONAL, THE MAXIUM NUMBER OF CONNECTIONS TO ALLOW PER TIME FRAME
      # - RATE_LIMIT_WINDOW_MS=1000 # OPTIONAL, TIME FRAME FOR WHICH REQUESTS ARE CHECKED IN MS
      - WEB_VERSION=${WEB_VERSION} # OPTIONAL, THE VERSION OF WHATSAPP WEB TO USE
      - WEB_VERSION_CACHE_TYPE=${WEB_VERSION_CACHE_TYPE} # OPTIONAL, DETERMINES WHERE TO GET THE WHATSAPP WEB VERSION(local, remote or none), DEFAULT 'none'
      # - RECOVER_SESSIONS=TRUE # OPTIONAL, SHOULD WE RECOVER THE SESSION IN CASE OF PAGE FAILURES
    volumes:
      - ./sessions:/usr/src/app/sessions
      - ./patches/chatController.js:/usr/src/app/src/controllers/chatController.js:ro
    depends_on:
      - chatbridge

  chatbridge:
    container_name: chatbridge_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CHATWOOT_BASE_URL=${CHATWOOT_BASE_URL}
      - WHATSAPP_BASE_URL=${WHATSAPP_BASE_URL}
      - WHATSAPP_TOKEN=${WHATSAPP_TOKEN}
      - LISTEN_PORT=${LISTEN_PORT}
      - SYSTEM_PHONE_NUMBER=${SYSTEM_PHONE_NUMBER}
    depends_on:
      postgres:
        condition: service_healthy
